"""create donation model

Revision ID: 192b9888f9bb
Revises: 40c6bfe00824
Create Date: 2024-04-10 13:19:09.040698

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '192b9888f9bb'
down_revision = '40c6bfe00824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
