"""create donation model

Revision ID: 205ba68c00c8
Revises: d203653dfb3a
Create Date: 2024-04-10 12:32:24.699918

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205ba68c00c8'
down_revision = 'd203653dfb3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_column('fully_invested')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('fully_invested', sa.BOOLEAN(), nullable=True)
        )

    # ### end Alembic commands ###
