"""create donation model

Revision ID: 3cbc2ae007ea
Revises: 5bad26b9abc2
Create Date: 2024-04-10 13:32:16.928373

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cbc2ae007ea'
down_revision = '5bad26b9abc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
