"""create donation model

Revision ID: 40c6bfe00824
Revises: 205ba68c00c8
Create Date: 2024-04-10 12:33:41.931740

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c6bfe00824'
down_revision = '205ba68c00c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
