"""edits2

Revision ID: 5146ce0cab4d
Revises: fd44e18dd2ba
Create Date: 2024-04-13 11:19:07.231851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5146ce0cab4d'
down_revision = 'fd44e18dd2ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
