"""create donation model

Revision ID: 5bad26b9abc2
Revises: ef7b63026554
Create Date: 2024-04-10 13:30:26.125684

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bad26b9abc2'
down_revision = 'ef7b63026554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
