"""edits2

Revision ID: 7718ab5d869f
Revises: 5146ce0cab4d
Create Date: 2024-04-13 11:19:31.678599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7718ab5d869f'
down_revision = '5146ce0cab4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
