"""create donation model

Revision ID: c5eeec522164
Revises: 192b9888f9bb
Create Date: 2024-04-10 13:20:16.671982

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5eeec522164'
down_revision = '192b9888f9bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('fully_invested', sa.Boolean(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_column('fully_invested')

    # ### end Alembic commands ###
