"""create donation model

Revision ID: ef7b63026554
Revises: c5eeec522164
Create Date: 2024-04-10 13:27:05.896435

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef7b63026554'
down_revision = 'c5eeec522164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
