"""Edits1

Revision ID: fd44e18dd2ba
Revises: 3cbc2ae007ea
Create Date: 2024-04-11 12:54:39.064273

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd44e18dd2ba'
down_revision = '3cbc2ae007ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
